// Basic .gql file type declarations
// Specific operation and fragment types are generated by the vite plugin in corresponding .d.ts files
declare module '*.gql' {
  import type { DocumentNode } from '@apollo/client';
  const document: DocumentNode;
  export default document;
}
