/*
 * @Author: ssq
 * @Date: 2022-06-09 09:26:44
 * @Description:
 */
declare module "angular-oauth2-oidc/oauth-service" {
  interface OAuthService {
    getIdentityClaims(this: this): IdentityClaims;
  }
}

// Generated by https://quicktype.io
export interface IdentityClaims {
  nbf: number;
  exp: number;
  iss: string;
  aud: string;
  nonce: string;
  iat: number;
  at_hash: string;
  s_hash: string;
  sid: string;
  sub: string;
  auth_time: number;
  idp: string;
  amr: string[];
  picture: string;
  role: string;
  email: string;
  phone_number: string;
  name: string;
  nickname: string;
  __tenant: string;
  preferred_username: string;
  email_verified: boolean;
  login_provider: string;
}
