version: "3.1"

services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: u5ern@me
            MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: u5ern@me
            ME_CONFIG_MONGODB_ADMINPASSWORD: P@ssw0rd
        links:
            - mongo
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        restart: always
