overwrite: true
schema:
  - ./src/app/shared/graphql/schema.graphql
  - http://x_proj_x.api.dev.x_org_x.com/graphql
# extensions:
#   endpoints:
#     default:
#       url: "https://x_proj_x.api.dev.x_org_x.com/graphql"
#       headers:
#         Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEiLCJsb2dpbl9wcm92aWRlciI6IlRydXN0ZWQifQ.MLw-_WPkvIsTI_QICxR8tiOJhGRSGWI3bVNoXUm1Fhw
documents:
  - "./src/**/*.graphql"
  - "!./src/**/*.test.graphql"
  - "!./src/**/test.graphql"
exclude: "./geex-schematics/**/*"
generates:
  ./src/app/shared/graphql/.generated/type.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
    config:
      declarationKind: "interface"
      documentMode: "graphQLTag"
      defaultScalarType: "any"
      scalars:
        ChinesePhoneNumberType: "string"
        DateTime: "Date"
        Decimal: "number"
        Long: "BigInt"
        ObjectId: "string"
      documentVariableSuffix: "Gql"
      fragmentVariableSuffix: "Gql"
  ./src/app/shared/graphql/.generated/apollo-helpers.ts:
    plugins:
      - typescript-apollo-client-helpers
config:
  declarationKind: "interface"
  enumsAsTypes: false
