// Auto-generated type declarations for importing .gql files
// Generated by vite-plugin-gqlgen. Do not edit.
declare module '*.gql' {
  import type { DocumentNode } from '@apollo/client';
  const document: DocumentNode;
  export default document;
}

declare module '*.graphql' {
  import type { DocumentNode } from '@apollo/client';
  const document: DocumentNode;
  export default document;
}
