# Query to get active settings
query GetActiveSettings {
  activeSettings {
    ...SettingInfo
  }
}

query OrgCount($orgName: String!) {
  orgs(filter: { name: { eq: $orgName } }) {
    totalCount
  }
}

# Mutation to create setting
mutation editSetting($name: SettingDefinition!, $value: Any!) {
  editSetting(request: {
    name: $name
    value: $value
  }) {
    ...SettingInfo
  }
}
