packages:
  - geex-angular
  - geex-extensions-settings
  - geex-extensions-multi-tenant
  - geex-extensions-identity
  - geex-extensions-authentication
  - geex-extensions-authorization
  - geex-extensions-authentication-wechat
  - geex-extensions-mocking
  - geex-extensions-blob-storage
  - geex-extensions-approval-flows
