name: Build and Publish NuGet Package

on:
  push:
    branches:
       - '*'

jobs:
  build-and-publish-nuget-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.203

      - name: Restore dependencies
        run: dotnet restore .\modules\Geex.Platform\server\Geex.Bms.sln

      - name: Build package
        run: dotnet pack --configuration Release   -o ./nupkg/ --no-build  --include-source  .\modules\Geex.Platform\server\Geex.Bms.sln

     
