name: Build and Publish NuGet Package

on:
  create:
    tags:
      - '*'

jobs:
  build-and-publish-nuget-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.203

      - name: Print tag name
        run: echo "Tag name:" +  ${GITHUB_REF//\// }






