name: publish
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test tags in format of refs/tags/v*'
        required: true
        type: string
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish-nuget-package:
    runs-on: ubuntu-latest
    env:
      PACKAGE_DESCRIPTION: "Geex - A modern dev-friendly framework for building scalable and maintainable applications"
      PACKAGE_AUTHOR: "Geex Team"
      PACKAGE_COMPANY: "Geex"
      PACKAGE_COPYRIGHT: "Copyright © Geex Team"
      PACKAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/136053225?s=64&v=4"
      PACKAGE_PROJECT_URL: "https://github.com/geex-framework/geex"
      PACKAGE_LICENSE_URL: "https://github.com/geex-framework/geex/blob/main/LICENSE"
      PACKAGE_REPOSITORY_URL: "https://github.com/geex-framework/geex"
      PACKAGE_TAGS: "geex;framework;dotnet;mongodb;graphql;cqrs"
    steps:
      - name: extract-version-from-input
        if: ${{ '$GITHUB_REF' == '' }}
        run: |
            echo "ref=$VERSION" >> $GITHUB_ENV

      - name: extract-version-from-ref
        if: ${{ '$GITHUB_REF' != '' }}
        run: |
            echo "ref=$GITHUB_REF" >> $GITHUB_ENV

      - name: Extract version number
        id: version
        run: |
          REF=${{env.ref}}
          echo "Ref name is $REF"
          if [[ "${REF#refs/tags/v}" =~ ^([0-9|\.]+)-?([a-z]+[0-9]*)?$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            SUFFIX="${BASH_REMATCH[2]}"
            echo "Extracted version and suffix from prerelease tag."
            echo "version=$VERSION"
            echo "suffix=$SUFFIX"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "suffix=$SUFFIX" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.300
          
      - name: Restore dependencies
        run: dotnet restore ./framework_modules/framework_modules.sln
        
      - name: Build projects
        run: |
          dotnet build --configuration Release ./framework_modules/Geex.Analyzer/src/Geex.Analyzer.csproj
          dotnet build --configuration Release ./framework_modules/framework_modules.sln /p:IncludeSourceGeneratedFiles=true
        
      - name: Generate NuGet release packages
        if: ${{ steps.version.outputs.suffix == '' }}
        env:
          VERSION: ${{ steps.version.outputs.version }}
          SUFFIX: ${{ steps.version.outputs.suffix }}
        run: |
          PROJECTS=(
            "./framework_modules/Geex.Casbin/src/Geex.Casbin.csproj"
            "./framework_modules/Geex.MongoDB.Entities/src/Geex.MongoDB.Entities.csproj"
            "./framework_modules/Geex.Common/src/Geex.Common.csproj"
            "./framework_modules/Geex.Abstractions/src/Geex.Abstractions.csproj"
            "./framework_modules/Geex.Extensions.AuditLogs/src/Geex.Extensions.AuditLogs.csproj"
            "./framework_modules/Geex.Analyzer/src/Geex.Analyzer.csproj"
            "./framework_modules/Geex.Extensions.Authentication/src/Geex.Extensions.Authentication.csproj"
            "./framework_modules/Geex.Extensions.Authorization/src/Geex.Extensions.Authorization.csproj"
            "./framework_modules/Geex.Extensions.BackgroundJob/src/Geex.Extensions.BackgroundJob.csproj"
            "./framework_modules/Geex.Extensions.BlobStorage/src/Geex.Extensions.BlobStorage.csproj"
            "./framework_modules/Geex.Extensions.Identity/src/Geex.Extensions.Identity.csproj"
            "./framework_modules/Geex.Extensions.Logging/src/Geex.Extensions.Logging.csproj"
            "./framework_modules/Geex.Extensions.Messaging/src/Geex.Extensions.Messaging.csproj"
            "./framework_modules/Geex.Extensions.MultiTenant/src/Geex.Extensions.MultiTenant.csproj"
            "./framework_modules/Geex.Extensions.Settings/src/Geex.Extensions.Settings.csproj"
            "./framework_modules/Geex.MediatX/MediatX/MediatX.csproj"
            "./framework_modules/Geex.MediatX/MediatX.RabbitMQ/MediatX.RabbitMQ.csproj"
          )
          
          for project in "${PROJECTS[@]}"; do
            dotnet pack "$project" \
              --configuration Release \
              --no-build \
              --output ./nupkg \
              /p:PackageVersion=${{env.VERSION}} \
              /p:Description="${{env.PACKAGE_DESCRIPTION}}" \
              /p:Authors="${{env.PACKAGE_AUTHOR}}" \
              /p:Company="${{env.PACKAGE_COMPANY}}" \
              /p:Copyright="${{env.PACKAGE_COPYRIGHT}}" \
              /p:PackageIconUrl="${{env.PACKAGE_LOGO_URL}}" \
              /p:PackageProjectUrl="${{env.PACKAGE_PROJECT_URL}}" \
              /p:PackageLicenseUrl="${{env.PACKAGE_LICENSE_URL}}" \
              /p:RepositoryUrl="${{env.PACKAGE_REPOSITORY_URL}}" \
              /p:PackageTags="${{env.PACKAGE_TAGS}}"
          done

      - name: Generate NuGet prerelease packages
        if: ${{ steps.version.outputs.suffix != '' }}
        env:
          VERSION: ${{ steps.version.outputs.version }}
          SUFFIX: ${{ steps.version.outputs.suffix }}
        run: |
          PROJECTS=(
            "./framework_modules/Geex.Casbin/src/Geex.Casbin.csproj"
            "./framework_modules/Geex.MongoDB.Entities/src/Geex.MongoDB.Entities.csproj"
            "./framework_modules/Geex.Common/src/Geex.Common.csproj"
            "./framework_modules/Geex.Abstractions/src/Geex.Abstractions.csproj"
            "./framework_modules/Geex.Extensions.AuditLogs/src/Geex.Extensions.AuditLogs.csproj"
            "./framework_modules/Geex.Analyzer/src/Geex.Analyzer.csproj"
            "./framework_modules/Geex.Extensions.Authentication/src/Geex.Extensions.Authentication.csproj"
            "./framework_modules/Geex.Extensions.Authorization/src/Geex.Extensions.Authorization.csproj"
            "./framework_modules/Geex.Extensions.BackgroundJob/src/Geex.Extensions.BackgroundJob.csproj"
            "./framework_modules/Geex.Extensions.BlobStorage/src/Geex.Extensions.BlobStorage.csproj"
            "./framework_modules/Geex.Extensions.Identity/src/Geex.Extensions.Identity.csproj"
            "./framework_modules/Geex.Extensions.Logging/src/Geex.Extensions.Logging.csproj"
            "./framework_modules/Geex.Extensions.Messaging/src/Geex.Extensions.Messaging.csproj"
            "./framework_modules/Geex.Extensions.MultiTenant/src/Geex.Extensions.MultiTenant.csproj"
            "./framework_modules/Geex.Extensions.Settings/src/Geex.Extensions.Settings.csproj"
            "./framework_modules/Geex.MediatX/MediatX/MediatX.csproj"
            "./framework_modules/Geex.MediatX/MediatX.RabbitMQ/MediatX.RabbitMQ.csproj"
          )
          
          for project in "${PROJECTS[@]}"; do
            dotnet pack "$project" \
              --configuration Release \
              --no-build \
              --version-suffix ${{env.SUFFIX}} \
              --output ./nupkg \
              /p:PackageVersion=${{env.VERSION}} \
              /p:Description="${{env.PACKAGE_DESCRIPTION}}" \
              /p:Authors="${{env.PACKAGE_AUTHOR}}" \
              /p:Company="${{env.PACKAGE_COMPANY}}" \
              /p:Copyright="${{env.PACKAGE_COPYRIGHT}}" \
              /p:PackageIconUrl="${{env.PACKAGE_LOGO_URL}}" \
              /p:PackageProjectUrl="${{env.PACKAGE_PROJECT_URL}}" \
              /p:PackageLicenseUrl="${{env.PACKAGE_LICENSE_URL}}" \
              /p:RepositoryUrl="${{env.PACKAGE_REPOSITORY_URL}}" \
              /p:PackageTags="${{env.PACKAGE_TAGS}}"
          done

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
